export const ORDER_STATUS = {
	WAIT_ACCEPT: 'WAIT_ACCEPT',
	WAIT_PAY: 'WAIT_PAY',
	PAID_WAIT_MAKE: 'PAID_WAIT_MAKE',
	MAKING: 'MAKING',
	WAIT_PICKUP: 'WAIT_PICKUP',
	WAIT_DELIVERY: 'WAIT_DELIVERY',
	DELIVERING: 'DELIVERING',
	COMPLETED: 'COMPLETED',
	REFUNDING: 'REFUNDING',
	REFUNDED: 'REFUNDED',
	CANCELED: 'CANCELED'
}

export const ORDER_STATUS_TEXT = {
	[ORDER_STATUS.WAIT_ACCEPT]: '待接单',
	[ORDER_STATUS.WAIT_PAY]: '待支付',
	[ORDER_STATUS.PAID_WAIT_MAKE]: '已支付/待制作',
	[ORDER_STATUS.MAKING]: '制作中',
	[ORDER_STATUS.WAIT_PICKUP]: '待自提',
	[ORDER_STATUS.WAIT_DELIVERY]: '待配送',
	[ORDER_STATUS.DELIVERING]: '配送中',
	[ORDER_STATUS.COMPLETED]: '已完成',
	[ORDER_STATUS.REFUNDING]: '退款中',
	[ORDER_STATUS.REFUNDED]: '已退款',
	[ORDER_STATUS.CANCELED]: '已取消'
}

export const PICKUP_TYPE = {
	SELF_PICKUP: 'SELF_PICKUP',
	DELIVERY: 'DELIVERY'
}

export const PICKUP_TYPE_TEXT = {
	[PICKUP_TYPE.SELF_PICKUP]: '到店自提',
	[PICKUP_TYPE.DELIVERY]: '商家配送'
}

export const ORDER_SOURCE = {
	PRODUCT: 'PRODUCT',
	CUSTOM: 'CUSTOM',
	CASE: 'CASE'
}

export const THEME_OPTIONS = [
	{ label: '生日', value: '生日' },
	{ label: '节日', value: '节日' },
	{ label: '成人', value: '成人' },
	{ label: '儿童', value: '儿童' },
	{ label: '老人', value: '老人' }
]

export const ORDER_ACTIONS = {
	CANCEL: 'cancel',
	PAY: 'pay',
	REFUND: 'refund',
	AFTER_SALE: 'afterSale'
}

export const PAYMENT_METHOD = {
	OFFLINE: 'OFFLINE',
	WECHAT: 'WECHAT'
}

export const PAYMENT_METHOD_TEXT = {
	[PAYMENT_METHOD.OFFLINE]: '线下确认',
	[PAYMENT_METHOD.WECHAT]: '微信支付'
}

export const USER_CANCELABLE_ORDER_STATUSES = [ORDER_STATUS.WAIT_ACCEPT, ORDER_STATUS.PAID_WAIT_MAKE]

export const USER_REBUY_ORDER_STATUSES = [ORDER_STATUS.COMPLETED, ORDER_STATUS.CANCELED, ORDER_STATUS.REFUNDED]

export const USER_AFTER_SALE_ORDER_STATUSES = [ORDER_STATUS.COMPLETED]

export const UPLOAD_BIZ_TYPE = {
	ORDER_REF: 'ORDER_REF',
	AFTER_SALE: 'AFTER_SALE'
}
